# Generated by Django 2.1.1 on 2018-10-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'verbose_name': 'Item group', 'verbose_name_plural': 'Item groups'},
        ),
    ]
