# Generated by Django 2.1.1 on 2018-10-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181016_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item group Translation',
                'db_table': 'inventory_itemgroup_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ItemGroup', verbose_name='Item group'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.UnitOfMeasure', verbose_name='Unit of measure'),
        ),
        migrations.AddField(
            model_name='itemgrouptranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventory.ItemGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='itemgrouptranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
