# Generated by Django 2.2.9 on 2020-01-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_unitofmeasure_company'),
        ('inventory', '0006_auto_20190122_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.Company'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.Company'),
        ),
    ]
