# Generated by Django 2.2.9 on 2020-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgrouptranslation',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemtranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
