# Generated by Django 2.2.10 on 2020-06-29 11:22

from django.db import migrations, models
from parler.models import TranslatableModelMixin

def forwards_func(apps, schema_editor):
    UnitOfMeasure = apps.get_model("general", "UnitOfMeasure")
    ItemGroup = apps.get_model("inventory", "ItemGroup")
    ItemGroup.__bases__ = (models.Model, TranslatableModelMixin)
    ItemGroupTranslation = apps.get_model("inventory", "ItemGroupTranslation")
    Item = apps.get_model("inventory", "Item")
    Item.__bases__ = (models.Model, TranslatableModelMixin)
    ItemTranslation = apps.get_model("inventory", "ItemTranslation")

    UnitOfMeasure.objects.create(
        id = 0,
        company_id = 1,
        name = '--------',
        description = 'empty value',
        active = False,
    )

    ItemGroup.objects.create(
        id = 0,
        company_id = 1,
    )

    ItemGroupTranslation.objects.create(
        id = 0,
        language_code = 'lt',
        name = '--------',
        description = 'empty value',
        master_id = 0,
    )

    Item.objects.create(
        id = 0,
        company_id = 1,
        item_group_id = 0,
        unit_of_measure_id = 0,
        active = False,
        price = 0,
    )

    ItemTranslation.objects.create(
        id = 0,
        language_code = 'lt',
        name = '--------',
        description = 'empty value',
        master_id = 0,
    )

def reverse_func(apps, schema_editor):
    UnitOfMeasure = apps.get_model("general", "UnitOfMeasure")
    Item = apps.get_model("inventory", "Item")
    ItemTranslation = apps.get_model("inventory", "ItemTranslation")
    ItemGroup = apps.get_model("inventory", "ItemGroup")
    ItemGroupTranslation = apps.get_model("inventory", "ItemGroupTranslation")

    ItemTranslation.objects.filter(id=0).delete()
    Item.objects.filter(id=0).delete()
    ItemGroupTranslation.objects.filter(id=0).delete()
    ItemGroup.objects.filter(id=0).delete()
    UnitOfMeasure.objects.filter(id=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200129_1530'),
        ('general', '0017_auto_20200623_1412'),
        ('receivables', '0020_auto_20200305_1539'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
