# Generated by Django 2.1.1 on 2018-09-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_system_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
