# Generated by Django 2.1.1 on 2018-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='web_site',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
