# Generated by Django 2.1.1 on 2018-10-16 12:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_company_web_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Fax No.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Fax No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Fax No.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Post code'),
        ),
    ]
