# Generated by Django 2.1.1 on 2018-10-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('general', '0007_auto_20181019_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'verbose_name': 'Unit of measure', 'verbose_name_plural': 'Units of measure'},
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='description',
            field=models.CharField(max_length=60, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Name'),
        ),
    ]
