# Generated by Django 2.2.9 on 2020-01-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.Company'),
        ),
    ]
