# Generated by Django 2.2.9 on 2020-02-14 14:02

from django.db import migrations, models
import shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_unitofmeasure_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shared.utils.get_image_path, verbose_name='change logo'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
