# Generated by Django 2.2.9 on 2020-02-24 13:23

from django.db import migrations 

def gen_domain(apps, shcema_editor):
    Company = apps.get_model('general', 'Company')
    for row in Company.objects.all():
        row.domain = str(row.id) + '.timeon.no'
        row.save(update_fields=['domain'])

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_company_domain'),
    ]

    operations = [
        migrations.RunPython(gen_domain, reverse_code=migrations.RunPython.noop),
    ]
