# Generated by Django 2.2.10 on 2020-06-23 12:11

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20200224_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('key', models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='key')),
                ('type', models.SmallIntegerField(choices=[(0, 'Boolean'), (1, 'Integer'), (3, 'Decimal'), (4, 'String'), (5, 'Option'), (6, 'Multiple options')], default=1, verbose_name='type')),
            ],
            options={
                'verbose_name': 'configuration key',
                'verbose_name_plural': 'configuration keys',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigTree',
            fields=[
                ('key', models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='key')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_key', default='ROOT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='values', to='general.ConfigTree', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'configuration tree node',
                'verbose_name_plural': 'configuration tree nodes',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='value')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.Company')),
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='general.ConfigKey', verbose_name='key')),
            ],
            options={
                'verbose_name': 'configuration value',
                'verbose_name_plural': 'configuration values',
            },
        ),
        migrations.CreateModel(
            name='ConfigTreeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=250, verbose_name='object name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='general.ConfigTree')),
            ],
            options={
                'verbose_name': 'configuration tree node Translation',
                'db_table': 'general_configtree_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ConfigKeyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=250, verbose_name='object name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('metadata', models.TextField(blank=True, default='', verbose_name='metadata')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='general.ConfigKey')),
            ],
            options={
                'verbose_name': 'configuration key Translation',
                'db_table': 'general_configkey_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='configkey',
            name='node',
            field=models.ForeignKey(db_column='node_key', on_delete=django.db.models.deletion.PROTECT, related_name='config_keys', to='general.ConfigTree', verbose_name='key node'),
        ),
        migrations.AddConstraint(
            model_name='configvalue',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_configkey'),
        ),
        migrations.AlterUniqueTogether(
            name='configtreetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='configkeytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
