# Generated by Django 2.2.10 on 2020-06-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200622_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtree',
            name='parent',
            field=models.ForeignKey(db_column='parent_key', default='ROOT', on_delete=django.db.models.deletion.PROTECT, related_name='values', to='general.ConfigTree', verbose_name='parent'),
        ),
    ]
