# Generated by Django 2.2.28 on 2022-09-25 12:59

from django.db import migrations
from django.db import models


def forwards_func(apps, schema_editor):

    User = apps.get_model("djauth", "User")
    ContentType = apps.get_model("contenttypes", "ContentType")
    CalendarType = apps.get_model("general", "CalendarType")

    ct = ContentType.objects.get_for_model(User)

    CalendarType.objects.create(
        # Creating Staff Holiday calendar
        id = 1,
        name = 'STAFF HOLIDAY',
        owner_type = ct
    )

    CalendarType.objects.create(
        # Creating Staff Absence due to illness calendar
        id = 2,
        name = 'STAFF ILLNESS',
        owner_type = ct
    )

    CalendarType.objects.create(
        # Creating Unjustified Absence calendar
        id = 3,
        name = 'STAFF UNJUSTIFIED ABSENCE',
        owner_type = ct
    )

def reverse_func(apps, schema_editor):
    CalendarType = apps.get_model("general", "CalendarType")
    CalendarType.objects.filter(id__in=[1,2,3]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20220924_1225'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
