# Generated by Django 2.2.28 on 2023-02-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_new_calendar_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarline',
            name='dfr',
        ),
        migrations.RemoveField(
            model_name='calendarline',
            name='dto',
        ),
        migrations.RemoveField(
            model_name='calendarline',
            name='tfr',
        ),
        migrations.RemoveField(
            model_name='calendarline',
            name='tto',
        ),
        migrations.AddField(
            model_name='calendarline',
            name='dtfr',
            field=models.DateTimeField(default='2020-01-01', verbose_name='from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarline',
            name='dtto',
            field=models.DateTimeField(default='2020-01-01', verbose_name='to'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='calendarheader',
            index=models.Index(fields=['owner_type', 'owner_id'], name='general_cal_owner_t_c1a798_idx'),
        ),
    ]
