# Generated by Django 2.1.1 on 2018-11-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20181024_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone No.'),
        ),
    ]
