# Generated by Django 2.1.1 on 2018-09-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField(choices=[(100, 'Company'), (200, 'Person')], default=100)),
                ('active', models.BooleanField(default=True)),
                ('web_site', models.CharField(blank=True, default='', max_length=250)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='general.Address')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bill', to='general.Address')),
                ('contact', models.ManyToManyField(blank=True, related_name='customer', to='general.Contact', verbose_name='Contacts')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ship', to='general.Address')),
            ],
        ),
    ]
