# Generated by Django 2.1.1 on 2018-09-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_unitofmeasure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date_time', models.DateTimeField(auto_now=True, verbose_name='Created date/time')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Discount amount')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Discount percent')),
                ('created_date_time', models.DateTimeField(auto_now=True, verbose_name='Created date/time')),
                ('last_modified_date_time', models.DateTimeField(auto_now=True, verbose_name='Last modified date/time')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Sales order',
                'verbose_name_plural': 'Sales orders',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Price')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Discount amount')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Discount percent')),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Line amount')),
                ('created_date_time', models.DateTimeField(auto_now=True, verbose_name='Created date/time')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.Item', verbose_name='Item')),
                ('sales_order_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receivables.SalesOrderHeader', verbose_name='Order')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='general.UnitOfMeasure', verbose_name='Unit of measure')),
            ],
            options={
                'verbose_name': 'Sales order line',
                'verbose_name_plural': 'Sales order lines',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='general.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bill', to='general.Address', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=32, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ship', to='general.Address', verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Company'), (200, 'Person')], default=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='web_site',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Web site'),
        ),
        migrations.AddField(
            model_name='salesorderheader',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='receivables.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='salesorderheader',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='salesorderheader',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='receivables.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='receivables.Customer', verbose_name='Customer'),
        ),
    ]
