# Generated by Django 2.1.1 on 2018-09-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_auto_20180924_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='salesorderheader',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesorderheader',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='salesorderheader',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='salesorderheader',
            name='last_modified_date_time',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='created_date_time',
        ),
    ]
