# Generated by Django 2.1.1 on 2018-10-19 10:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_auto_20181016_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street address'),
        ),
    ]
