# Generated by Django 2.1.1 on 2018-10-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0005_auto_20181019_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
    ]
