# Generated by Django 2.1.1 on 2018-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0006_remove_customer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderheader',
            name='amount',
        ),
        migrations.AddField(
            model_name='salesorderheader',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Estimated amount'),
        ),
    ]
