# Generated by Django 2.1.1 on 2018-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0007_auto_20181022_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderheader',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
