# Generated by Django 2.1.1 on 2018-10-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('salary', '0003_auto_20181022_2107'),
        ('receivables', '0008_salesorderheader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date_time', models.DateTimeField(auto_now=True, verbose_name='Created date/time')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.Employee')),
            ],
            options={
                'verbose_name': 'Work time journal',
                'verbose_name_plural': 'Work time journal',
            },
        ),
        migrations.AlterModelOptions(
            name='salesorderheader',
            options={'ordering': ['-id'], 'verbose_name': 'Sales order', 'verbose_name_plural': 'Sales orders'},
        ),
    ]
