# Generated by Django 2.1.1 on 2018-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0009_auto_20181022_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderheader',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Description'),
        ),
    ]
