# Generated by Django 2.1.1 on 2018-10-31 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20181024_1457'),
        ('receivables', '0010_auto_20181024_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receivables.Project')),
                ('sales_order_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receivables.SalesOrderHeader')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', through='receivables.RelatedEmployee', to='salary.Employee', verbose_name='Employees'),
        ),
        migrations.AddField(
            model_name='salesorderheader',
            name='employees',
            field=models.ManyToManyField(related_name='sales_orders', through='receivables.RelatedEmployee', to='salary.Employee', verbose_name='Employees'),
        ),
    ]
