# Generated by Django 2.1.1 on 2018-10-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0011_auto_20181031_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedemployee',
            options={'verbose_name': 'Related employee', 'verbose_name_plural': 'Related employees'},
        ),
        migrations.AlterField(
            model_name='relatedemployee',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receivables.Project'),
        ),
    ]
