# Generated by Django 2.1.1 on 2018-10-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20181024_1457'),
        ('receivables', '0012_auto_20181031_2259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatedemployee',
            unique_together={('employee', 'sales_order_header'), ('employee', 'project')},
        ),
    ]
