# Generated by Django 2.1.1 on 2018-11-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181031_2132'),
        ('salary', '0005_auto_20181114_1025'),
        ('receivables', '0013_auto_20181031_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimejournal',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='diet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Diet'),
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='salary.Employee', verbose_name='Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='ferry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ferry'),
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='inventory.Item', verbose_name='Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='toll_ring',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Toll ring'),
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='work_date',
            field=models.DateField(default='2010-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='work_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Work time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='work_time_from',
            field=models.TimeField(default='00:00', verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimejournal',
            name='work_time_to',
            field=models.TimeField(default='00:00', verbose_name='To'),
            preserve_default=False,
        ),
    ]
