# Generated by Django 2.2.10 on 2020-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0019_auto_20200207_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimejournal',
            name='parking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Parking'),
        ),
    ]

