# Generated by Django 2.2.10 on 2020-06-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0020_auto_20200305_1539'),
        ('inventory', '0021_add_item_0_as_empty_value_20200629_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimejournal',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='worktimejournal',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='inventory.Item', verbose_name='Item'),
        ),
    ]
